# Generated by Django 2.0.2 on 2019-04-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='blog_url',
            field=models.CharField(default='', max_length=50, verbose_name='博客地址'),
        ),
        migrations.AddField(
            model_name='blogorg',
            name='category',
            field=models.CharField(choices=[('bkpt', '博客平台'), ('gr', '个人')], default='gr', max_length=20, verbose_name='博客类别'),
        ),
    ]
