# Generated by Django 2.0.2 on 2019-04-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20190413_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='blogger/%Y/%m', verbose_name='头像'),
        ),
    ]
