# Generated by Django 2.0.2 on 2019-04-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
