# Generated by Django 2.0.2 on 2019-04-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_blogger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='blogger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Blogger', verbose_name='所属博主'),
        ),
    ]
