# Generated by Django 2.0.2 on 2019-04-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_blogposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='category',
            field=models.CharField(blank=True, choices=[('py', 'python'), ('ja', 'java'), ('C', 'C++'), ('zw', '杂文')], max_length=2, null=True, verbose_name='文章分类'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('py', 'python'), ('ja', 'java'), ('C', 'C++'), ('zw', '杂文')], max_length=2, null=True, verbose_name='文章分类'),
        ),
    ]
