# Generated by Django 2.0.2 on 2019-04-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20190415_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='desc',
            field=models.CharField(max_length=300, null=True, verbose_name='文章描述'),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='detail',
            field=models.TextField(verbose_name='文章详情'),
        ),
    ]
