# Generated by Django 2.0.2 on 2019-04-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20190415_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('py', 'python'), ('ja', 'java'), ('C', 'C++'), ('zw', '杂文')], max_length=2, null=True, verbose_name='文章分类'),
        ),
    ]
