# Generated by Django 2.0.2 on 2019-04-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20190413_1114'),
        ('course', '0009_auto_20190415_1723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPosts',
            new_name='Posts',
        ),
    ]
