# Generated by Django 2.0.2 on 2019-04-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20190413_1114'),
        ('course', '0010_auto_20190415_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='BlogPosts',
        ),
    ]
