# Generated by Django 2.0.2 on 2019-04-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20190416_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogposts',
            old_name='Like_nums',
            new_name='like_nums',
        ),
    ]
