# Generated by Django 2.0.2 on 2019-04-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20190424_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='nandu',
            field=models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], max_length=2, null=True, verbose_name='难度'),
        ),
    ]
