# Generated by Django 2.0.2 on 2019-04-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_auto_20190425_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_url',
            field=models.CharField(default='', max_length=100, verbose_name='章节网址'),
        ),
    ]
