# Generated by Django 2.0.2 on 2019-04-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_lesson_lesson_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AddField(
            model_name='blogposts',
            name='blog_url',
            field=models.CharField(default='', max_length=100, verbose_name='网址'),
        ),
    ]
