# Generated by Django 2.0.2 on 2019-04-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20190412_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '教程'), (2, '博客文章'), (3, '博主')], default=1, verbose_name='收藏类型'),
        ),
    ]
